Refactor redraw with search
Shougo/ddu.vim pull request #41
Opened 2023-01-14 12:06 UTC by hori-ryota

- redraw周りを「ui側も含めたデータの更新」と「uiのredraw」に整理しました
- 「ui側も含めたデータの更新」処理でexpandとsearch対象の解決をしました

これ自体は良さそうなのですが、再表示でrefreshが発生すると挙動がおかしい問題に当たったので、ちょっと調査します
https://github.com/Shougo/ddu.vim/blob/7d1b1fab5f1098e0c8c12246e34a78acfd144584/denops/ddu/ddu.ts#L150

2023-01-14 15:52 UTC, hori-ryota commented
wait to merge followings

- [fix \`\_\_expanded\` mismatch bug by hori\-ryota · Pull Request \#40 · Shougo/ddu\.vim](https://github.com/Shougo/ddu.vim/pull/40)
- [refactor flags to cancel context by hori\-ryota · Pull Request \#43 · Shougo/ddu\.vim](https://github.com/Shougo/ddu.vim/pull/43)

2023-01-15 03:07 UTC, Shougo commented
I have merged above PRs.

2023-01-15 03:16 UTC, Shougo requested changes
Please rebase it.

2023-01-15 03:59 UTC, hori-ryota commented on denops/ddu/ddu.ts
> +          return this.redraw(denops);
本当はredrawではなくuiRedrawにしたいですが、searchPathからsearchItemを拾う手段がないので妥協です。
tree復元にexpandItemが叩かれ直す（gatherItemがそれぞれ走る）のでuiRedrawに対し少しパフォーマンスが落ちます。

検討した回避策は以下ですが、どちらも微妙でした。

* `searchedItem` をメモしておく
    * expandされているが別itemにカーソルがあるとき、searchPathのitemを得る手段がなくカーソルの動かし先がわからない
* `searchedPath` の親がexpandedか確認する
    * expandedでなければredrawする、expandedならuiRedrawする、と考えると自然だが、前案に同じくexpandedだった場合にカーソルの動かし先がわからない

`ui.searchPath` が復活すればうまく動かせますが、消したinterfaceを復活させる話になるのでいったん妥協でいいかなと思っています

2023-01-15 04:04 UTC, hori-ryota commented on denops/ddu/ddu.ts
> +      // apply only defined by new options
optionで指定しているのでどの挙動を正とするかはちょっと迷っています。

- 上書きされた場合のみ反映
    - → 現在のカーソルが他にあり、再度searchしたい場合に意図と反する。
- optionを空で更新しない限りは常にsearchする
    - → 妥当ではありそうだが好みは分かれそう
- 明示的に指定したときのみsearchする（今）
    - → 妥当ではありそうだが好みは分かれそう

2023-01-15 04:05 UTC, hori-ryota commented
再表示時の挙動は良くなったと思うのですが、ファイル作成＆削除時の再描画が怪しいのでもうちょっとデバッグします

2023-01-15 04:32 UTC, Shougo commented on denops/ddu/ddu.ts
> +          return this.redraw(denops);
ここは妥協でよいと思います

2023-01-15 04:34 UTC, hori-ryota commented
https://github.com/Shougo/ddu.vim/blob/6d62834bcb37a2faa0ff3ad4d109400ecf60deed/denops/ddu/ddu.ts#L758-L766

でquitted = trueになっているのでrefreshが走らなくなりますね。

2023-01-15 04:34 UTC, Shougo commented on denops/ddu/ddu.ts
> +      (search == undefined || isParentPath(parent.treePath, search))
ここの変更の意図を教えてください

2023-01-15 04:35 UTC, hori-ryota commented
> でquitted = trueになっているのでrefreshが走らなくなりますね。

quittedをrefresh & redraw前に戻すことで直りました

2023-01-15 04:37 UTC, Shougo commented on denops/ddu/ddu.ts
> +      // apply only defined by new options
これは迷うところですが現在の実装でよいのではないかと。

2023-01-15 04:37 UTC, Shougo commented on denops/ddu/ddu.ts
> +      // apply only defined by new options
ただし、ドキュメントの修正は必要そう

2023-01-15 04:37 UTC, Shougo commented on denops/ddu/ddu.ts
> +    await this.uiRedraw(denops);
ここの変更の意図を教えてください

2023-01-15 04:48 UTC, hori-ryota commented on denops/ddu/ddu.ts
> +      (search == undefined || isParentPath(parent.treePath, search))
searchしないがmaxLevelまで展開したい場合に、

expand判定のところだと

- maxLevelまで全て展開する
- searchはしないのでexpandedなものだけmaxLevelまで展開する

の区別がつかず、またsearchのところだと

- カーソルを展開したものに動かしたい（ `searchedItem` にparentを入れたい）
- 展開はするがカーソルを動かしたくない（ `searchedItem` を更新しない）

の区別がつかないため、

- `undefined` で指定される = 未指定として旧来の挙動をする
- 空文字で指定する = 明示的にsearchしないことを示す

と判定できるようにした意図です。

https://github.com/Shougo/ddu.vim/pull/41/files#diff-2f3633cb841d3456918702b7f466a9d7e41f8b8f4cf788aa94b10b717f199391R505

でダミーとして空文字が入ると無限に展開されてしまったのでその対応でした。

2023-01-15 04:50 UTC, hori-ryota commented on denops/ddu/ddu.ts
> +      (search == undefined || isParentPath(parent.treePath, search))
たぶん

- searchを用いる展開（maxLevelは制限として使う）
- searchを用いずmaxLevelだけ展開する

の2つの挙動が一つのインターフェースで提供されていて難しくなりがちなところなので、組み合わせをunion typeとかで定義してどっちの挙動をしたいのか明確にしてみるのがいいかもですね

2023-01-15 05:43 UTC, hori-ryota commented on denops/ddu/ddu.ts
> +    await this.uiRedraw(denops);
ui.refreshItemはredrawの責務にしたので、uiRedrawはitemsを引数に取らなくてよくなりました。そのため第2引数が不要になっています。

2023-01-15 05:49 UTC, hori-ryota commented on denops/ddu/ddu.ts
> +      // apply only defined by new options
一応ドキュメントを更新してみました。

2023-01-15 06:38 UTC, Shougo commented on denops/ddu/ddu.ts
> +      (search == undefined || isParentPath(parent.treePath, search))
なるほど。確かにその挙動は複雑なので、union 使ったほうがよいような

2023-01-16 07:11 UTC, hori-ryota commented on denops/ddu/ddu.ts
> +      (search == undefined || isParentPath(parent.treePath, search))
リファクタしてみました

2023-01-16 07:18 UTC, hori-ryota commented on denops/ddu/ddu.ts
> +      if (restoreItemState) {
filter済みのものはgather stateのものと参照先が違うようでstateの復旧が必要になりました

2023-01-17 00:27 UTC, Shougo requested changes
バグ報告: narrow action がうまく動作していません。手元でも調査しますが修正をお願いします。

2023-01-17 00:33 UTC, Shougo commented
あと、絞り込みのときに再描画がやけに遅いのも気になっています。

2023-01-17 02:35 UTC, hori-ryota commented
> バグ報告: narrow action がうまく動作していません。手元でも調査しますが修正をお願いします。

`sourceOptions.path` が変更になるとtreePathの構成が変わる（子に行くのは問題ない）ので不具合出ていそうですね。ちょっとみてみます

2023-01-17 02:58 UTC, hori-ryota commented
expandedPathの管理をsourceOptions.pathごとにしました

2023-01-17 03:02 UTC, hori-ryota commented
> あと、絞り込みのときに再描画がやけに遅いのも気になっています。

こちらもう少し詳しくいただけますか？

2023-01-17 03:03 UTC, hori-ryota commented
ファイルを開いてuiを閉じたときにquittedが正しくない症状を確認したので対応します

2023-01-17 03:13 UTC, hori-ryota commented
deleteやnewFile時にactionOptionがquite:trueで処理されるようなので原因を調査中です

2023-01-17 03:15 UTC, hori-ryota commented
`defaultActionOptions` が `{
    quit: true,
  }` なんですねなるほど

2023-01-17 03:26 UTC, hori-ryota commented
[Quit UI before action](https://github.com/Shougo/ddu.vim/blob/6d62834bcb37a2faa0ff3ad4d109400ecf60deed/denops/ddu/ddu.ts#L758) の理由を伺ってもいいですか？
quitされるとrefreshなどのデータ取得フローを止める（contextチェックにquittedを含めている）ので、refreshする場合にどうしたいか判断したく

2023-01-17 03:40 UTC, hori-ryota commented
あー、ファイルを開くときに閉じておかないとdduの画面で開いちゃうんですね、なるほど

2023-01-17 04:00 UTC, hori-ryota commented
いったんrefreshとredrawのときだけquittedを戻すようにしました。

これにより新規ファイル作成時に挙動が変わりました

- 旧：ファイルを開き、uiを閉じる
- 新：ファイルを開き、該当ファイルをsearchした状態になる

2023-01-17 07:08 UTC, Shougo commented
ありがとうございます。確認します

2023-01-17 07:10 UTC, Shougo commented
> >  あと、絞り込みのときに再描画がやけに遅いのも気になっています。

> こちらもう少し詳しくいただけますか？

これについてはもうちょっと動作を見てみます。

2023-01-17 07:15 UTC, Shougo commented
色々修正は入っているようですが、narrow action の不具合はまだ直ってないですよね。

2023-01-17 07:17 UTC, Shougo commented on denops/ddu/ddu.ts
> +      this.quitted = false;
ここ以外もそうですが、コメントの行頭は他に揃えて大文字にしてください。

2023-01-17 08:01 UTC, hori-ryota commented
お、手元だとexpandedPathsをmapにしたことでnarrowの挙動の一つは直ったと思うのですが、どういうバグでしょうか

2023-01-17 10:03 UTC, Shougo commented
確かに最小構成では動作していますね。これは調査します。

2023-01-17 10:04 UTC, Shougo commented
あ、わかりました。これは仕様通りです。私が勘違いしていた。問題ありません。

2023-01-17 10:06 UTC, Shougo commented
コメントの問題さえ直れば一度マージしてよいと思っています。何か懸念点はありますか。

2023-01-17 10:19 UTC, hori-ryota commented
指摘いただいている再描画時の挙動、expandedPathsの節約、パフォーマンスチューニング、quitでrefreshが中断されたあとの起動時にrefreshしたい、など改善したいところはありますが、このプルリクとしてはマージしてよいかと思いますー！

2023-01-17 10:21 UTC, Shougo approved these changes

2023-01-17 10:21 UTC, Shougo commented
一度マージします

2023-01-17 10:21 UTC, merged